version: 0.2

phases:
  install:
    commands:
      - echo ===install===
#      - echo install nodejs 12...
#      - curl -fsSL https://deb.nodesource.com/setup_12.x | bash
#      - apt install -y nodejs
  pre_build:
    commands:
      - echo ===pre-build===
#      - echo installing dependencies
#      - npm install
      - echo Deployment started on `date`
      - echo sync S3 content
      - aws s3 sync ./build/ s3://dailybookkeeping.com.au
  build:
    commands:
      - echo ===build===
#      - npm run build
      - echo cloudfront cache invalidation...
      - aws cloudfront create-invalidation --distribution-id E3SMALSVRZKFHH --paths "/*"
  post_build:
    commands:
      - echo ===post_build===
      - echo Deployment completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build

