version: 0.2

phases:
  install:
    commands:
      - echo ===install===
      - echo install nodejs 12...
      - curl -fsSL https://deb.nodesource.com/setup_12.x | bash
      - apt install -y nodejs
  pre_build:
    commands:
      - echo ===pre-build===
  build:
    commands:
      - echo ===build===
      - npm run build
  post_build:
    commands:
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build

